import 'dotenv/config';
import mongoose from 'mongoose';
import { AdtuCourse } from '../models/AdtuCourse';

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb+srv://school-management:school-management@cluster0.tk0qz.mongodb.net/multi_agent_system?retryWrites=true&w=majority&appName=Cluster0';

const ADTU_COURSES = [
  // ── UNDERGRADUATE (UG) COURSES ──────────────────────────────────────────
  {
    courseCode: 'ADTU-UG-CSE',
    courseName: 'B.Tech in Computer Science & Engineering',
    degreeLevel: 'UG',
    department: 'Faculty of Engineering & Technology',
    durationYears: 4,
    durationSemesters: 8,
    annualTuitionFee: 147500,
    totalTuitionFee: 590000,
    eligibilityCriteria: 'Passed 10+2 with Physics, Chemistry, and Mathematics (PCM) with minimum 50% aggregate marks (45% for SC/ST). Selection via JEE Main / Assam CEE / AdtU Entrance Test.',
    minPercentageRequired: 50,
    acceptedStreams: ['Science (PCM)'],
    entranceExamsRequired: ['JEE Main', 'Assam CEE', 'AdtU Entrance Test'],
    specializations: ['Artificial Intelligence & Machine Learning', 'Cyber Security', 'Cloud Computing', 'Data Science'],
    careerOpportunities: ['Software Engineer', 'Full Stack Developer', 'Data Analyst', 'Cloud Architect'],
    placementPartners: ['IBM', 'TCS', 'Wipro', 'Capgemini', 'Infosys'],
    isPopular: true,
    isActive: true,
  },
  {
    courseCode: 'ADTU-UG-BCA',
    courseName: 'Bachelor of Computer Applications (BCA)',
    degreeLevel: 'UG',
    department: 'Faculty of Computer Applications',
    durationYears: 3,
    durationSemesters: 6,
    annualTuitionFee: 80000,
    totalTuitionFee: 240000,
    eligibilityCriteria: 'Passed 10+2 in any stream (Science, Commerce, or Arts) with minimum 45% aggregate marks (40% for reserved category). Mathematics / Computer Science in 10+2 preferred.',
    minPercentageRequired: 45,
    acceptedStreams: ['Science', 'Commerce', 'Arts'],
    entranceExamsRequired: ['Merit-based', 'AdtU Counseling'],
    specializations: ['Web Development', 'Software Engineering', 'Mobile App Development'],
    careerOpportunities: ['Web Developer', 'System Administrator', 'Software Tester', 'Database Assistant'],
    placementPartners: ['Wipro', 'Tech Mahindra', 'Cognizant', 'AdtU Tech Labs'],
    isPopular: true,
    isActive: true,
  },
  {
    courseCode: 'ADTU-UG-BPHARM',
    courseName: 'Bachelor of Pharmacy (B.Pharm)',
    degreeLevel: 'UG',
    department: 'Faculty of Pharmaceutical Science',
    durationYears: 4,
    durationSemesters: 8,
    annualTuitionFee: 205000,
    totalTuitionFee: 820000,
    eligibilityCriteria: 'Passed 10+2 with Physics, Chemistry, and Biology/Mathematics (PCB/PCM) with minimum 60% aggregate marks and English as a subject. Approved by Pharmacy Council of India (PCI).',
    minPercentageRequired: 60,
    acceptedStreams: ['Science (PCB)', 'Science (PCM)'],
    entranceExamsRequired: ['AdtU Pharmacy Entrance', 'Merit-based'],
    specializations: ['Pharmaceutics', 'Pharmacology', 'Pharmaceutical Chemistry'],
    careerOpportunities: ['Pharmacist', 'Drug Inspector', 'Medical Representative', 'Quality Assurance Manager'],
    placementPartners: ['Sun Pharma', 'Cipla', 'Lupin', 'Torrent Pharma', 'Apollo Pharmacy'],
    isPopular: true,
    isActive: true,
  },
  {
    courseCode: 'ADTU-UG-NURSING',
    courseName: 'B.Sc in Nursing',
    degreeLevel: 'UG',
    department: 'Faculty of Nursing',
    durationYears: 4,
    durationSemesters: 8,
    annualTuitionFee: 120000,
    totalTuitionFee: 480000,
    eligibilityCriteria: 'Passed 10+2 with Physics, Chemistry, Biology (PCB) and English with minimum 45% aggregate marks. Minimum age 17 years as on Dec 31. Recognized by Indian Nursing Council (INC).',
    minPercentageRequired: 45,
    acceptedStreams: ['Science (PCB)'],
    entranceExamsRequired: ['State Nursing Entrance', 'AdtU Nursing Test'],
    specializations: ['Critical Care Nursing', 'Pediatric Nursing', 'Community Health Nursing'],
    careerOpportunities: ['Registered Nurse', 'Clinical Instructor', 'Hospital Supervisor', 'Healthcare Specialist'],
    placementPartners: ['Apollo Hospitals', 'down town hospital', 'Fortis', 'Max Healthcare'],
    isPopular: true,
    isActive: true,
  },
  {
    courseCode: 'ADTU-UG-BBA',
    courseName: 'Bachelor of Business Administration (BBA)',
    degreeLevel: 'UG',
    department: 'Faculty of Management',
    durationYears: 3,
    durationSemesters: 6,
    annualTuitionFee: 70000,
    totalTuitionFee: 210000,
    eligibilityCriteria: 'Passed 10+2 in any stream (Commerce, Science, or Arts) with minimum 45% aggregate marks from a recognized board.',
    minPercentageRequired: 45,
    acceptedStreams: ['Commerce', 'Science', 'Arts'],
    entranceExamsRequired: ['Merit-based', 'AdtU Interview'],
    specializations: ['Digital Marketing', 'Finance & Banking', 'Human Resource Management'],
    careerOpportunities: ['Business Analyst', 'Marketing Executive', 'HR Executive', 'Sales Manager'],
    placementPartners: ['HDFC Bank', 'ICICI Bank', 'Axis Bank', 'Reliance Retail'],
    isPopular: false,
    isActive: true,
  },
  {
    courseCode: 'ADTU-UG-BMLT',
    courseName: 'B.Sc in Medical Laboratory Technology (BMLT)',
    degreeLevel: 'UG',
    department: 'Faculty of Paramedical Sciences',
    durationYears: 3.5,
    durationSemesters: 7,
    annualTuitionFee: 80000,
    totalTuitionFee: 280000,
    eligibilityCriteria: 'Passed 10+2 with Physics, Chemistry, and Biology (PCB) with minimum 45% aggregate marks.',
    minPercentageRequired: 45,
    acceptedStreams: ['Science (PCB)'],
    entranceExamsRequired: ['Merit-based'],
    specializations: ['Clinical Pathology', 'Hematology', 'Microbiology'],
    careerOpportunities: ['Lab Technologist', 'Pathology Specialist', 'Research Assistant'],
    placementPartners: ['down town hospital', 'Dr Lal PathLabs', 'Metropolis Healthcare'],
    isPopular: false,
    isActive: true,
  },
  {
    courseCode: 'ADTU-UG-CIVIL',
    courseName: 'B.Tech in Civil Engineering',
    degreeLevel: 'UG',
    department: 'Faculty of Engineering & Technology',
    durationYears: 4,
    durationSemesters: 8,
    annualTuitionFee: 117500,
    totalTuitionFee: 470000,
    eligibilityCriteria: 'Passed 10+2 with Physics, Chemistry, and Mathematics (PCM) with minimum 50% aggregate marks.',
    minPercentageRequired: 50,
    acceptedStreams: ['Science (PCM)'],
    entranceExamsRequired: ['JEE Main', 'Assam CEE', 'AdtU Entrance Test'],
    specializations: ['Structural Engineering', 'Transportation Engineering'],
    careerOpportunities: ['Civil Engineer', 'Site Supervisor', 'Structural Designer'],
    placementPartners: ['L&T', 'Gammon India', 'PWD Assam'],
    isPopular: false,
    isActive: true,
  },

  // ── POSTGRADUATE (PG) COURSES ──────────────────────────────────────────
  {
    courseCode: 'ADTU-PG-MBA',
    courseName: 'Master of Business Administration (MBA)',
    degreeLevel: 'PG',
    department: 'Faculty of Management',
    durationYears: 2,
    durationSemesters: 4,
    annualTuitionFee: 180000,
    totalTuitionFee: 360000,
    eligibilityCriteria: 'Passed Bachelor’s Degree in any discipline (B.A, B.Sc, B.Com, B.Tech, BBA, BCA) with minimum 50% aggregate marks (45% for SC/ST). Selection based on CAT/MAT/CMAT/XAT or AdtU MAT + Group Discussion and Personal Interview (GD/PI).',
    minPercentageRequired: 50,
    acceptedStreams: ['Any Graduation Degree'],
    entranceExamsRequired: ['CAT', 'MAT', 'CMAT', 'XAT', 'AdtU MAT'],
    specializations: ['Marketing & Digital Business', 'Finance & FinTech', 'Human Resource Management', 'Healthcare & Hospital Management'],
    careerOpportunities: ['Brand Manager', 'Financial Analyst', 'HR Business Partner', 'Operations Manager', 'Hospital Administrator'],
    placementPartners: ['Amul', 'ITC', 'HDFC Bank', 'Bandhan Bank', 'Flipkart', 'Deloitte'],
    isPopular: true,
    isActive: true,
  },
  {
    courseCode: 'ADTU-PG-MCA',
    courseName: 'Master of Computer Applications (MCA)',
    degreeLevel: 'PG',
    department: 'Faculty of Computer Applications',
    durationYears: 2,
    durationSemesters: 4,
    annualTuitionFee: 90000,
    totalTuitionFee: 180000,
    eligibilityCriteria: 'Passed BCA / B.Sc in Computer Science/IT or Bachelor’s Degree in any stream with Mathematics at 10+2 level or Graduation level with minimum 50% aggregate marks (45% for SC/ST).',
    minPercentageRequired: 50,
    acceptedStreams: ['BCA', 'B.Sc (CS/IT)', 'Graduation with Maths'],
    entranceExamsRequired: ['Assam JCAAT', 'AdtU Entrance Test', 'Merit-based'],
    specializations: ['Full Stack Web Development', 'Cloud & DevOps', 'Data Analytics'],
    careerOpportunities: ['Senior Software Engineer', 'Full Stack Developer', 'System Architect', 'Data Engineer'],
    placementPartners: ['TCS', 'Wipro', 'IBM', 'Accenture', 'Cognizant'],
    isPopular: true,
    isActive: true,
  },
  {
    courseCode: 'ADTU-PG-MTECH',
    courseName: 'M.Tech in Computer Science & Engineering',
    degreeLevel: 'PG',
    department: 'Faculty of Engineering & Technology',
    durationYears: 2,
    durationSemesters: 4,
    annualTuitionFee: 80000,
    totalTuitionFee: 160000,
    eligibilityCriteria: 'Passed B.E / B.Tech in Computer Science / IT or equivalent degree with minimum 50% aggregate marks. GATE score preferred.',
    minPercentageRequired: 50,
    acceptedStreams: ['B.Tech / B.E (CSE/IT)'],
    entranceExamsRequired: ['GATE', 'AdtU Test'],
    specializations: ['Artificial Intelligence', 'Data Science', 'Networks'],
    careerOpportunities: ['Research Scientist', 'AI Engineer', 'Assistant Professor'],
    placementPartners: ['TCS Research', 'Wipro', 'Academic Institutions'],
    isPopular: false,
    isActive: true,
  },
  {
    courseCode: 'ADTU-PG-MSC-BIOTECH',
    courseName: 'M.Sc in Biotechnology',
    degreeLevel: 'PG',
    department: 'Faculty of Sciences',
    durationYears: 2,
    durationSemesters: 4,
    annualTuitionFee: 75000,
    totalTuitionFee: 150000,
    eligibilityCriteria: 'Passed B.Sc in Biotechnology, Microbiology, Botany, Zoology, or Life Sciences with minimum 50% aggregate marks.',
    minPercentageRequired: 50,
    acceptedStreams: ['B.Sc Life Sciences / Biotech'],
    entranceExamsRequired: ['Merit-based', 'AdtU Test'],
    specializations: ['Molecular Biology', 'Industrial Biotechnology'],
    careerOpportunities: ['Biotech Researcher', 'Quality Control Officer', 'Lab Analyst'],
    placementPartners: ['Biocon', 'Serum Institute', 'Research Labs'],
    isPopular: false,
    isActive: true,
  },
  {
    courseCode: 'ADTU-PG-MPHARM',
    courseName: 'M.Pharm in Pharmaceutics',
    degreeLevel: 'PG',
    department: 'Faculty of Pharmaceutical Science',
    durationYears: 2,
    durationSemesters: 4,
    annualTuitionFee: 120000,
    totalTuitionFee: 240000,
    eligibilityCriteria: 'Passed B.Pharm from a PCI recognized institute with minimum 55% aggregate marks. GPAT qualified candidates preferred.',
    minPercentageRequired: 55,
    acceptedStreams: ['B.Pharm'],
    entranceExamsRequired: ['GPAT', 'AdtU Entrance'],
    specializations: ['Pharmaceutics', 'Pharmacology'],
    careerOpportunities: ['R&D Scientist', 'Formulation Specialist', 'Regulatory Affairs Manager'],
    placementPartners: ['Sun Pharma', 'Dr. Reddy’s', 'Cipla'],
    isPopular: false,
    isActive: true,
  },
];

export async function seedAdtuCourses() {
  try {
    if (mongoose.connection.readyState === 0) {
      await mongoose.connect(MONGODB_URI);
      console.log('✅ Connected to MongoDB Atlas for course seeding.');
    }

    let created = 0;
    let updated = 0;

    for (const c of ADTU_COURSES) {
      const res = await AdtuCourse.findOneAndUpdate(
        { courseCode: c.courseCode },
        c,
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
      if (res) created++;
    }

    console.log(`🎓 Assam Down Town University Course Seeding complete: ${created} courses synced.`);
  } catch (err: any) {
    console.error('❌ Failed to seed AdtU courses:', err.message || err);
  }
}

if (require.main === module) {
  seedAdtuCourses().then(() => process.exit(0));
}
